# 8-piece puzzle com busca em largura e A*

#### Códigos para criar a matriz, mover as peças e executar os algoritmos. Usamos uma classe Nó para representar nossa árvore. Cada nó tem um peso associado (só usado no A*), um pai, e uma lista de filhos. Para facilitar, também tem a solução armazenada, para contar o numero de peças fora do lugar.

In [1]:
import numpy as np
import random
import copy

def create_matrix (dimension):
    table = []
    k=1
    for i in range(0,dimension):
            table.append([])
            for j in range(0, dimension):
                table[i].append(k)
                k+=1
    table[-1][-1]=None
    return table


def count_misplaced (problem, solution):
    count = 0
    for i in range(0,len(problem)):
            for j in range(0, len(problem)):
                if problem[i][j] != solution [i][j]:
                    count+=1
    return count   


def find_blank (table):
    for i in range(len(table[0])):
        for j in range(len(table)):
            if table[i][j] == None:
                return i,j



def get_moves(table):
        
        pos = find_blank(table)
        moves = [
            (pos[0], pos[1]-1), #pra cima
            (pos[0], pos[1]+1), #pra baixo
            (pos[0]-1, pos[1]), #pra esquerda
            (pos[0]+1, pos[1]) #pra direita
        ]
        #movimentos que saem do tabuleiro
        moves = filter(lambda x: (x[0] >= 0 and x[1] >= 0 and x[0] < len(table)
                and x[1] < len(table)), moves)
        
        return list(moves)
    
def make_move (pos_value, table, moves):
    #move branco para pos e põe o numero que estava lá no lugar do branco
    new = copy.deepcopy(table)
    pos_none = find_blank(new)
    if pos_value in moves:
            temp = new [pos_value[0]][pos_value[1]]
            new[pos_value[0]][pos_value[1]] = None
            new[pos_none[0]][pos_none[1]] = temp
    return new

def shuffle (table):
    #faz movimentos aleatórios para embaralhar a tabela
    for i in range (0, 50):
        moves = get_moves(table)
        table = make_move(random.choice(moves), table, moves)
    return table


class Node:
    
    def __init__(self, table, solution, parent = None, height = 0):
        
        #pai do nó
        self.parent = parent
        
        #tabuleiro
        self.table = table
        
        #solucao
        self.solution = solution
        
        #lista de filhos
        self.children = list()
        
        #altura da árvore
        self.height = height
        
        
        self.weight = self.calculate_weight()
    
    def add_child(self, table):
        child = Node(table, parent=self, solution = self.solution, height = self.height+1)
        if not_equal(child):
            self.children.append(child)
    
    def calculate_weight(self):
        #heuristica
        h = count_misplaced (self.table, self.solution)
        return (h + self.height)
        
    
def not_equal(self):
        current = self.parent
        while current != None:
            if self.table == current.table:
                #existe o mesmo tabuleiro na linhagem, não gere esse filho
                return False
            current = current.parent
        return True

def generate_children(self):
        moves = get_moves(self.table)
        for i in range (0, len(moves)):
            child_table = make_move(moves[i], self.table, moves)
            self.add_child(child_table)
        return self.children

def bfs (problem, solution):
    i = 0
    #problema é solução
    if problem.table == solution:
        print ("Resolvido com ", i, "iterações")
        return problem
    #Gerando as primeiras possibilidades
    problem.children = []
    desc = generate_children(problem)
    #enquanto tiver possibilidades
    while len(desc) != 0:
        child = desc.pop(0)
        #achou solução
        if child.table == solution:
            del desc
            print ("BFS resolveu com ", i, "iterações")
            return child
        #se não for a solução, gera os filhos do filho atual e guarda no final da lista (pra ser em largura)
        generate_children(child)
        for x in child.children:
            desc.append(x)
        i+=1
    return None


def a_star (problem, solution):
    i = 0
    #problema é solução
    if problem.table == solution:
        print ("A* resolveu com ", i, "iterações")
        return problem
    #Gerando as primeiras possibilidades
    problem.children = []
    desc = generate_children(problem)
    #ordenando conforme A*
    desc.sort(key=lambda x: x.weight)
    #enquanto tiver possibilidades
    while len(desc) != 0:
        child = desc.pop(0)
        #achou solução
        if child.table == solution:
            del desc
            print ("A* resolveu com ", i, "iterações")
            return child
        #se não for a solução, gera os filhos do filho atual e adiciona a lista
        generate_children(child)
        for x in child.children:
            desc.append(x)
        #ordena a lista baseado na funcao do A*
        desc.sort(key=lambda x: x.weight)
        i+=1
    return None


def print_movimentos(solution):
    moves = []
    current = solution
    while current != None:
        moves.append(current.table)
        current = current.parent
    while True:
        print(np.matrix(moves[-1]))
        moves.pop(-1)
        if not moves:
            break
        print("")
        print("  | ")
        print("  | ")
        print(" \\\'/ \n")
        

### Código de teste

In [2]:
goal = create_matrix(3)
table =  shuffle(goal)
problem = Node(table, solution = goal)
solution_tree = bfs(problem, goal)
solution_tree = a_star(problem, goal)
print_movimentos(solution_tree)

BFS resolveu com  231 iterações
A* resolveu com  15 iterações
[[1 3 5]
 [7 4 2]
 [None 8 6]]

  | 
  | 
 \'/ 

[[1 3 5]
 [None 4 2]
 [7 8 6]]

  | 
  | 
 \'/ 

[[1 3 5]
 [4 None 2]
 [7 8 6]]

  | 
  | 
 \'/ 

[[1 3 5]
 [4 2 None]
 [7 8 6]]

  | 
  | 
 \'/ 

[[1 3 None]
 [4 2 5]
 [7 8 6]]

  | 
  | 
 \'/ 

[[1 None 3]
 [4 2 5]
 [7 8 6]]

  | 
  | 
 \'/ 

[[1 2 3]
 [4 None 5]
 [7 8 6]]

  | 
  | 
 \'/ 

[[1 2 3]
 [4 5 None]
 [7 8 6]]

  | 
  | 
 \'/ 

[[1 2 3]
 [4 5 6]
 [7 8 None]]
